### ISSUE TITLE
Razor go documentation to be updated for v1.0.5

### ISSUE THREAD

**Issue by Yashk767** [razor-network/docs-v2#64]
- [ ] Update vote command with docker run...
 - [x] Mention in the docs about risks of supplying a password and tell the user how to delete the command from history
 - [x] Mention backupNode flag info in vote command.
 - [x] SetConfig command needs to be updated

Few of these tasks where created in oracle-node repo here, https://github.com/razor-network/oracle-node/issues/942

**Comment by Shrikant1212** [comment]
Applying the restart flag to the vote command will spin a new container so there are multiple ways to handle that

1. Need to update all docker run command 
   Currently, we are running a single container, while keeping it's shell active, and we run all razor commands via the same container. 
    we need to update all commands to create their own container ie instead of using docker exec we have to run docker run for every razor command

    Previous:
`        docker exec -it razor-go razor <command>`
    New:
        `docker run -it  --name razor-go-vote -v "$(pwd)"/.razor:/home/razor/.razor <command>`

2. Can spin container with a new name

  Commands: 
       1. Start Voting
     
         `docker run -d -it --restart=always  --name razor-go-vote -v "$(pwd)"/.razor:/home/razor/.razor <latest-docker-iamge> vote --password /home/razor/.razor/password --address 0xaE6772eE682f786F62c4C3e02297e03c767F4F07`
       2. Stop vote command
        ` docker stop razor-go-vote`

  3. Remove the old container
   ` docker rm razor-go-vote`


3. Can spin container with no name

    Commands: 
    1. Start Voting
    `docker run -d -it --restart=always  -v "$(pwd)"/.razor:/home/razor/.razor <latest-image> vote --password /home/razor/.razor/password --address <address>`
    2. Get containerID
    `CONTAINER_ID=$(docker container ls  | grep 'razornetwork/razor-go' | awk '{print $1}')`

    2. Stop vote command
` docker stop $CONTAINER_ID`

    3. Remove the old container
    `docker rm $CONTAINER_ID`
